/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExchangeRate { 
    currency?: string | null;
    rate?: number | null;
    equivalentAmount?: number | null;
}

