/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MerchantInfo { 
    name?: string | null;
    taxId?: string | null;
    additionalInfo?: string | null;
}

