/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptData } from './receiptData';


export interface ReceiptResponse { 
    id: string;
    user_id: string;
    receipt_data: ReceiptData;
    merchant: string;
    total: number;
    date: string;
    image_url?: string | null;
    created_at: string;
}

