/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentInfo } from './paymentInfo';
import { ReceiptItem } from './receiptItem';
import { ExchangeRate } from './exchangeRate';
import { Discount } from './discount';
import { MerchantInfo } from './merchantInfo';
import { ServiceCharge } from './serviceCharge';
import { FinancialSummary } from './financialSummary';
import { TaxDetail } from './taxDetail';
import { Location } from './location';


export interface ReceiptData { 
    isValid: boolean;
    merchantInfo: MerchantInfo;
    location: Location;
    dateTime?: string | null;
    items: Array<ReceiptItem>;
    financialSummary: FinancialSummary;
    taxDetails?: Array<TaxDetail> | null;
    discounts?: Array<Discount> | null;
    serviceCharge?: ServiceCharge | null;
    paymentInfo: PaymentInfo;
    exchangeRate?: ExchangeRate | null;
    notes?: Array<string> | null;
    handwrittenNotes?: Array<string> | null;
}

