/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptData } from './receiptData';


export interface ReceiptUpdate { 
    receipt_data?: ReceiptData | null;
    image_url?: string | null;
}

