/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessingStatus } from './processingStatus';


export interface TaskStatusResponse { 
    /**
     * The task ID
     */
    id: string;
    user_id: string;
    status: ProcessingStatus;
    receipt_id?: string | null;
    error_message?: string | null;
    created_at: string;
    updated_at: string;
    image_url?: string | null;
    exception_details?: string | null;
}
export namespace TaskStatusResponse {
}


