/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaxDetail { 
    rate?: string | null;
    taxableAmount?: number | null;
    taxAmount?: number | null;
    totalWithTax?: number | null;
    currency: string;
}

