/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginResponse { 
    access_token: string;
    token_type?: string;
    refresh_token: string;
    expires_in: number;
    expires_at: number;
}

