/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskListResponse } from './taskListResponse';


export interface PaginatedResponseTaskListResponse { 
    items: Array<TaskListResponse>;
    total: number;
    limit: number;
    offset: number;
    has_more: boolean;
}

