/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptListResponse } from './receiptListResponse';


export interface PaginatedResponseReceiptListResponse { 
    items: Array<ReceiptListResponse>;
    total: number;
    limit: number;
    offset: number;
    has_more: boolean;
}

