/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentInfo { 
    type?: string | null;
    terminalId?: string | null;
    transactionId?: string | null;
    slip?: string | null;
    bankCardType?: string | null;
}

