/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessingStatus } from './processingStatus';


export interface ReceiptProcessingResponse { 
    task_id: string;
    status: ProcessingStatus;
    message: string;
}
export namespace ReceiptProcessingResponse {
}


