/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReceiptListResponse { 
    id: string;
    user_id: string;
    merchant?: string | null;
    total: number;
    currency?: string | null;
    date: string | null;
    image_url?: string | null;
    created_at: string;
}

