/**
 * Receipt Manager API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReceiptListResponse {
    id: string;
    user_id: string;
    merchant: string;
    total: number;
    currency: string;
    date: string;
    image_url?: string | null;
    created_at: string;
}

