/**
 * Receipt Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessingStatus } from './processingStatus';


export interface TaskListResponse { 
    id: string;
    user_id: string;
    status: ProcessingStatus;
    receipt_id?: string | null;
    error_message?: string | null;
    created_at: string;
    updated_at: string;
    llm_error?: { [key: string]: any; } | null;
}
export namespace TaskListResponse {
}


