services:
  - type: web
    name: receipt-manager
    container_name: receipt-manager-ui
    env: static
    buildCommand: npm install && npm run build-app
    staticPublishPath: ./dist/receipt-manager
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 